#=
Test against hashes generated by xxhash Python package binding to xxHash C code.

```
# $ pip install xxhash

import xxhash, random, string

hashes = []
alphabet = list(string.ascii_letters) + list(map(lambda x: str(x), range(10)))

for seed in range(3):
    seeded_hashes = []

    for l in range(1, 25):
        s = "".join(random.choices(alphabet, k=l))
        h = xxhash.xxh32(s, seed=seed).intdigest()
        seeded_hashes.append((s, h))

    hashes.append(seeded_hashes)

print(hashes)
```
=#

targets = [[("v", 1259630150),
  ("a8", 1835359114),
  ("fUq", 985741357),
  ("mSGU", 2366716683),
  ("aVbS4", 2390168688),
  ("6auApz", 665432590),
  ("JSDTAVI", 4282733323),
  ("YF7yfRK7", 2262460641),
  ("652LA7NsD", 2387938605),
  ("7v94Vcf6ii", 1633368240),
  ("waCfVs8ghkT", 2126304637),
  ("sdYcTG42SxFS", 3573072939),
  ("zXiTWAtAA96Ad", 2193871919),
  ("b1Vj5dtsktfNuc", 3763414697),
  ("0CPwqq90LLbSRAR", 4240991465),
  ("3VeNJ9k87ADPQP2l", 1106953083),
  ("08HSTVGSMta6tSXdJ", 2707097053),
  ("XfGxrE5We6JqgnyqJ3", 2630788709),
  ("GxkO2df4lvnNsMS0P3q", 522766024),
  ("kyALEqhDTFAe71sXV1Zo", 1409462946),
  ("t0nX006K8140dcgfp7U0W", 2172031615),
  ("2JcusR6Ks4MKhT1mTtgTQY", 641606598),
  ("TljbLM8mFwCYC58pAeUNLrG", 1185234769),
  ("dKVCyP3AqRMVEsmEcxz2jBRf", 3929560640)],
 [("6", 3515247229),
  ("c4", 549536168),
  ("f4X", 4025520750),
  ("1FdF", 631362957),
  ("0qDuh", 1741377569),
  ("3V4zMc", 2157674019),
  ("10DA2Rc", 2326775583),
  ("Pzbk91D7", 1976643304),
  ("pSBaZnota", 3063072841),
  ("qe8lmMY1E6", 1593297606),
  ("zBnuTyR82g7", 3119470027),
  ("1D0C1qQW3wOP", 720299753),
  ("Xesl7xeHl3ROi", 3047398370),
  ("cHEGns8W0g079c", 153747316),
  ("Uizs3kD1kCJ6SGg", 3861815016),
  ("s1Se8zeSt6IGpdFv", 544518291),
  ("ygtC4A9YEliGjBDQi", 3044239291),
  ("Pz5nbYMkUeSEcBFhHg", 3596167015),
  ("nXZT51UKQ985clGRNOj", 265041030),
  ("c2akoJ4K4J6bGine4pVw", 2694955038),
  ("W01z2emFcTRjUgiYjP5NV", 600037851),
  ("57fezuSRoktJLyANkgeQr8", 2534380311),
  ("vV3ticwcJPK6NY2ypJEGxsG", 4096128641),
  ("6aiR7VPe9AgKKExWHlMKfcWk", 613628952)],
 [("V", 1422054787),
  ("EV", 269605434),
  ("2tf", 3497175211),
  ("WMgg", 1892868900),
  ("riJMu", 2457402509),
  ("VX9noG", 744706234),
  ("Dg9oFUZ", 59713237),
  ("beQrGyPv", 1724197544),
  ("C8DM3xnTZ", 3870677197),
  ("SwD3zcMWel", 2213373059),
  ("PtsAkhy9tBj", 2155364224),
  ("mAHjp0207srO", 3190089913),
  ("mxKeg4AerayGx", 1142351837),
  ("2kIUvwKbXzrCI2", 167778931),
  ("kTwi4quZYHquUFA", 2794363786),
  ("kqz4wpmELmMoXp7g", 1135713681),
  ("wxcp8XAjKodjWw5ev", 2432161392),
  ("yA9bPMOXEU6E0nqDKe", 244192601),
  ("yKEUlrKBBHXbVbWvLPh", 3027512882),
  ("T2EHs2EImFJZGCufBDir", 3172495074),
  ("7fZIL23q70zoDwWrnMXmY", 709613360),
  ("bHVRnTETRIVlqMzVRfA2E8", 511570815),
  ("ZW8ozAMrMZzUAuI53NhzLNH", 3295020974),
  ("zauzpuj6Q5uFAqQIUpCvWYsa", 2834400596)]]

@testset "xxhash.jl" begin
    @testset "Test agreement of Julia and C implementations of xxHash32" begin
        for seed = 0:length(targets)-1
            for t = targets[seed+1]
                @test xxhash32(t[1], seed) == t[2]
            end
        end
    end
end

#=
More extensive testing:

```
using PyCall
@pyimport xxhash

@testset "Test agreement of Julia and C implementations of xxHash32" begin
    for seed in rand(UInt32, 10)
        for l in 1:100
            for _ = 1:100
                s = randstring(l)
                @test xxhash32(s, seed) == xxhash.xxh32(s, seed)[:intdigest]()
            end
        end
    end
end
```
=#
