language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly
after_success:
    - julia -e 'cd(Pkg.dir("LSMH")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
    - julia -e 'cd(Pkg.dir("LSMH")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
