language: julia
os:
  - linux
  - osx
julia:
  - 1.0
notifications:
  email: false
after_success:
    - |
        julia -e '
            using Pkg
            Pkg.add("Coverage")
            using Coverage
            Coveralls.submit(Coveralls.process_folder())
            Codecov.submit(Codecov.process_folder())'
